apiVersion: v1
kind: ServiceAccount
metadata:
  name: fusion-training-ksa
  namespace: fusion-training
  annotations:
    iam.gke.io/gcp-service-account: fusion-training-sa@YOUR_GCE_PROJECT.iam.gserviceaccount.com